parent: map-defaults

name: locations.eclipse_chambers.name

# = SPAWNERS

entities:
  monster-spawner:
    parent: spawner
    interval: 2
    radius: 1
    checker:
      type: MONSTER_SPAWNER
      radius: 5.0

  ogremagi:
    parent: entity
    type: OGREMAGI
    name: entities.monsters.ogremagi.name
    inventory:
    - item: ultimate-sword
      chance: 0.5
    - item: wooden-sword

  dropped-sword:
    parent: dropped-item
    item: custom-sword

# = ITEMS

items:
  custom-sword:
    parent: ultimate-sword
    name: items.weapons.custom.meme-sword.name
    damage: 100.0

# = PORTALS

portals:
  rottenville-eclipse-chambers:
    parent: portal
    destination: rottenville
    name: locations.rottenville.name
    spawn: rottenville-eclipse-chambers-spawn
  rottenville-eclipse-chambers-spawn:
    parent: portal-spawn