parent: map

name: locations.eclipse_chambers.name

# = SPAWNERS

entities:
  monster-spawner:
    parent: spawner
    interval: 2
    radius: 1
    checker:
      type: MONSTER_SPAWNER
      radius: 5.0

  ogremagi:
    parent: entity
    entity-type: OGREMAGI
    name: Ogremagi
    inventory:
    - item: ultimate-sword
      chance: 0.5
    - item: wooden-sword

  dropped-sword:
    parent: dropped-item
    item: ultimate-sword

# = ITEMS

items:
  custom-sword:
    parent: ultimate-sword
    name: Meme Sword
    damage: 100.0

# = PORTALS

portals:
  rottenville:
    destination: rottenville
    portal-id: rottenville-eclipse-chambers
    name: locations.rottenville.name