entities:
  entity:
    type: ENTITY
    count: 1

  dropped-item:
    parent: entity
    entity-type: DROPPED_ITEM

  spawner:
    parent: entity

    type: SPAWNER
    entity-type: MONSTER
    interval: 2.0
    radius: 1.0

  player:
    parent: entity
    entity-type: PLAYER

    # entity will be saved to the global repository
    # and won't be recreated every time
    shared: true

    inventory:
    - item: hand
      hotbar: 0
    - item: light-orb
    - item: beginner-staff
      index: 5
      hotbar: 2
    - item:
        parent: ultimate-sword
        name: ULTRA SWORD!11
      index: 10
      hotbar: 1
      chance: 0.5

meta:
  EMPTY:
    weight: 1.0
    passable: true
  SOLID:
    weight: 0.0
    passable: false
  WATER:
    weight: 0.0
    passable: false
  PATH:
    weight: 0.9
    passable: true