parent: map-defaults

name: locations.rottenville.name

# = SPAWNERS

entities:
  npc:
    parent: entity
    type: NPC
  nina:
    parent: npc
    name: entities.npc.nina.name
  zelda:
    parent: npc
    name: entities.npc.zelda.name
  elizabeth:
    parent: npc
    name: entities.npc.elizabeth.name
  lela:
    parent: npc
    name: entities.npc.lela.name
  dropped-sword:
    parent: dropped-item
    item: wooden-sword

# = PORTALS

portals:
  rottenville-eclipse-chambers:
    parent: portal
    destination: eclipse-chambers
    name: locations.eclipse_chambers.name
    spawn: rottenville-eclipse-chambers-spawn
  rottenville-eclipse-chambers-spawn:
    parent: portal-spawn