parent: map

name: locations.rottenville.name

# = SPAWNERS

entities:
  npc:
    parent: entity
    entity-type: NPC
  nina:
    parent: npc
    name: Nina
  zelda:
    parent: npc
    name: Zelda
  elizabeth:
    parent: npc
    name: Elizabeth
  lela:
    parent: npc
    name: Lela
  dropped-sword:
    parent: dropped-item
    item: wooden-sword

# = PORTALS

portals:
  eclipse-chambers:
    destination: eclipse-chambers
    portal-id: rottenville-eclipse-chambers
    name: locations.eclipse_chambers.name