parent: map

name: locations.rottenville.name

# = SPAWNERS

entities:
  npc:
    parent: entity
    type: NPC
  nina:
    parent: npc
    name: Nina
  zelda:
    parent: npc
    name: Zelda
  elizabeth:
    parent: npc
    name: Elizabeth
  lela:
    parent: npc
    name: Lela
  dropped-sword:
    parent: dropped-item
    item: wooden-sword

# = PORTALS

portals:
  rottenville-eclipse-chambers:
    parent: portal
    destination: eclipse-chambers
    name: locations.eclipse_chambers.name
    spawn: rottenville-eclipse-chambers-spawn
  rottenville-eclipse-chambers-spawn:
    parent: portal-spawn
